import React, { useMemo, useState } from 'react';
import { ArrowRight, ChartNoAxesCombined, Info } from 'lucide-react';
import { JsonRecord } from '../types';
import { analyzeConditionalTransitions, DEFAULT_TRANSITION_CONFIG, formatTransitionInterval, formatTransitionRate, TransitionConfig } from '../utils/transitionAnalytics';

interface ConditionalTransitionPanelProps { records: JsonRecord[]; }

function coefficientClass(value: number, targetMin: number): string {
  if (value >= targetMin) return 'border-rose-300 bg-rose-100 text-rose-800 dark:border-rose-800 dark:bg-rose-950/60 dark:text-rose-200';
  if (value > 1.45) return 'border-amber-300 bg-amber-100 text-amber-800 dark:border-amber-800 dark:bg-amber-950/50 dark:text-amber-200';
  return 'border-slate-300 bg-slate-100 text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200';
}

function formatDate(value: string): string {
  return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(value));
}

export const ConditionalTransitionPanel: React.FC<ConditionalTransitionPanelProps> = ({ records }) => {
  const [config, setConfig] = useState<TransitionConfig>(DEFAULT_TRANSITION_CONFIG);
  const result = useMemo(() => analyzeConditionalTransitions(records, config), [config, records]);
  const updateNumber = (field: keyof TransitionConfig, value: string) => {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) return;
    setConfig((current) => ({ ...current, [field]: parsed }));
  };
  const recentOccurrences = result.occurrences.slice(-30).reverse();

  return <section className="space-y-5 rounded-2xl border border-indigo-200 bg-white p-5 shadow-xs dark:border-indigo-900/70 dark:bg-slate-900" aria-labelledby="conditional-transition-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="rounded-xl bg-indigo-100 p-2 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300"><ChartNoAxesCombined className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-indigo-700 dark:text-indigo-300">Transitions conditionnelles</p><h3 id="conditional-transition-title" className="mt-1 text-base font-bold text-slate-900 dark:text-white">Que se passe-t-il après une séquence ?</h3><p className="mt-1 max-w-3xl text-[11px] text-slate-500 dark:text-slate-400">Analyse historique des positions +1 à +{config.lookahead} après une séquence de petits multiplicateurs, triée par date et heure.</p></div></div><span className="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-3 py-1.5 text-[10px] font-semibold text-indigo-800 dark:bg-indigo-950/50 dark:text-indigo-200"><Info className="h-3.5 w-3.5" />Taux observés uniquement</span></div>
    <div className="rounded-xl border border-indigo-100 bg-indigo-50/60 p-3 text-[11px] text-indigo-950 dark:border-indigo-900/50 dark:bg-indigo-950/20 dark:text-indigo-100"><strong>Condition analysée :</strong> {config.sequenceLength} résultat(s) consécutif(s) ≤ {config.conditionMax.toFixed(2)}x <ArrowRight className="mx-1 inline h-3.5 w-3.5" /> chaque position future est comparée au seuil ≥ {config.targetMin.toFixed(2)}x. Les dates distinctes indiquent sur combien de dates la condition a été observée.</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5"><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Longueur</span><input type="number" min="1" max="12" value={config.sequenceLength} onChange={(event) => updateNumber('sequenceLength', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Condition ≤</span><input type="number" min="0" step="0.05" value={config.conditionMax} onChange={(event) => updateNumber('conditionMax', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Cible ≥</span><input type="number" min="0" step="0.1" value={config.targetMin} onChange={(event) => updateNumber('targetMin', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Positions futures</span><input type="number" min="1" max="10" value={config.lookahead} onChange={(event) => updateNumber('lookahead', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Dates minimum</span><input type="number" min="1" max="365" value={config.minimumDistinctDates} onChange={(event) => updateNumber('minimumDistinctDates', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-950/40"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Conditions trouvées</p><p className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{result.conditionCount}</p><p className="text-[10px] text-slate-500 dark:text-slate-400">{result.distinctConditionDates} date(s) distincte(s)</p></div><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-3 dark:border-indigo-900/60 dark:bg-indigo-950/30"><p className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 dark:text-indigo-300">Données ordonnées</p><p className="mt-1 text-xl font-bold text-indigo-950 dark:text-indigo-100">{result.orderedValidCount}</p><p className="text-[10px] text-indigo-700 dark:text-indigo-300">date + heure valides</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 dark:border-amber-900/60 dark:bg-amber-950/30"><p className="text-[10px] font-bold uppercase tracking-wider text-amber-700 dark:text-amber-300">Lecture</p><p className="mt-1 text-sm font-bold text-amber-950 dark:text-amber-100">+1 à +{config.lookahead}</p><p className="text-[10px] text-amber-700 dark:text-amber-300">positions après la condition</p></div></div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-[980px] w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:bg-slate-950/70 dark:text-slate-400"><tr><th className="px-3 py-3 font-bold">Position</th><th className="px-3 py-3 font-bold">Résultats évalués</th><th className="px-3 py-3 font-bold">Cible ≥ {config.targetMin.toFixed(2)}x</th><th className="px-3 py-3 font-bold">Dates de la condition</th><th className="px-3 py-3 font-bold">Dates avec cible</th><th className="px-3 py-3 font-bold">Taux observé</th><th className="px-3 py-3 font-bold">Intervalle moyen</th><th className="px-3 py-3 font-bold">Intervalle dominant</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{result.positions.map((position) => <tr key={position.position} className="bg-white dark:bg-slate-900"><td className="px-3 py-3 font-bold text-indigo-700 dark:text-indigo-300">+{position.position}</td><td className="px-3 py-3">{position.evaluatedCount}</td><td className="px-3 py-3 font-semibold text-rose-700 dark:text-rose-300">{position.targetCount}</td><td className="px-3 py-3">{position.distinctConditionDates}</td><td className="px-3 py-3">{position.distinctTargetDates}</td><td className="px-3 py-3 font-bold text-emerald-700 dark:text-emerald-300">{formatTransitionRate(position.targetRate)}</td><td className="px-3 py-3 font-mono">{formatTransitionInterval(position.averageIntervalSeconds)}</td><td className="px-3 py-3">{position.dominantBand ? `${position.dominantBand.label} · ${formatTransitionRate(position.dominantBand.rate)}` : '—'}</td></tr>)}</tbody></table></div>
    <div><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><div><h4 className="text-sm font-bold text-slate-900 dark:text-white">Occurrences détaillées</h4><p className="text-[10px] text-slate-500 dark:text-slate-400">Les {Math.min(30, recentOccurrences.length)} dernières observations de la condition et de ses positions futures.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{result.occurrences.length} ligne(s)</span></div><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-[900px] w-full text-left text-[11px]"><thead className="bg-slate-50 text-[9px] uppercase tracking-wider text-slate-500 dark:bg-slate-950/70 dark:text-slate-400"><tr><th className="px-3 py-2">Date condition</th><th className="px-3 py-2">Position</th><th className="px-3 py-2">Date du résultat</th><th className="px-3 py-2">Multiplicateur</th><th className="px-3 py-2">Délai depuis condition</th><th className="px-3 py-2">Statut</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{recentOccurrences.length > 0 ? recentOccurrences.map((occurrence, index) => <tr key={`${occurrence.conditionTimestamp}-${occurrence.position}-${occurrence.timestamp}-${index}`}><td className="px-3 py-2 font-medium">{formatDate(occurrence.conditionTimestamp)}</td><td className="px-3 py-2 font-bold text-indigo-700 dark:text-indigo-300">+{occurrence.position}</td><td className="px-3 py-2 font-medium">{formatDate(occurrence.timestamp)}</td><td className="px-3 py-2"><span className={`inline-flex rounded-md border px-2 py-1 font-bold ${coefficientClass(occurrence.coefficient, config.targetMin)}`}>{occurrence.coefficient.toFixed(2)}x</span></td><td className="px-3 py-2 font-mono">{formatTransitionInterval(occurrence.intervalSeconds)}</td><td className="px-3 py-2 font-semibold">{occurrence.isTarget ? <span className="text-rose-700 dark:text-rose-300">Dans la cible</span> : <span className="text-slate-500 dark:text-slate-400">Autre intervalle</span>}</td></tr>) : <tr><td colSpan={6} className="px-4 py-8 text-center text-xs text-slate-500 dark:text-slate-400">Aucune condition trouvée avec les paramètres actuels.</td></tr>}</tbody></table></div></div>
    <p className="text-[10px] text-slate-500 dark:text-slate-400">Les taux sont calculés uniquement sur les lignes réellement présentes dans le JSON chargé. Ils ne constituent pas une prédiction ni une garantie du prochain tour.</p>
  </section>;
};
