import React, { useMemo, useState } from 'react';
import { BarChart3, ChevronDown, ChevronUp, Info } from 'lucide-react';
import { JsonRecord } from '../types';
import {
  analyzeRecurrences,
  formatRecurrenceCoefficient,
  formatRecurrencePercent,
  formatRecurrenceRange,
  RecurrenceGranularity,
  RecurrenceOccurrence,
  RecurrenceSlotSummary,
  RecurrenceWeekdaySummary,
} from '../utils/recurrenceSummary';

interface RecurrenceSummaryPanelProps {
  records: JsonRecord[];
  sourceName?: string;
}

function clampMinute(value: number): number {
  return Math.max(0, Math.min(1439, value));
}

function formatDate(timestamp: number): string {
  return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium' }).format(new Date(timestamp));
}

function formatTime(timestamp: number): string {
  return new Intl.DateTimeFormat('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(timestamp));
}

function formatDuration(seconds: number | null): string {
  if (seconds === null) return '—';
  const normalized = Math.max(0, Math.round(seconds));
  return `${String(Math.floor(normalized / 3600)).padStart(2, '0')}:${String(Math.floor((normalized % 3600) / 60)).padStart(2, '0')}:${String(normalized % 60).padStart(2, '0')}`;
}

function OccurrenceDetails({ occurrences, title, slotStartMinute }: { occurrences: RecurrenceOccurrence[]; title: string; slotStartMinute: number }) {
  return <div className="border-t border-cyan-100 bg-cyan-50/40 p-3 dark:border-cyan-900/50 dark:bg-cyan-950/20"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-800 dark:text-cyan-200">{title} · {occurrences.length} occurrence(s)</p><span className="text-[10px] text-cyan-700 dark:text-cyan-300">Détail chronologique complet</span></div><div className="overflow-x-auto rounded-lg border border-cyan-100 dark:border-cyan-900/50"><table className="min-w-[980px] w-full text-left text-[11px]"><thead className="bg-white/80 text-[9px] uppercase tracking-wider text-slate-500 dark:bg-slate-900/70 dark:text-slate-400"><tr><th className="px-3 py-2">#</th><th className="px-3 py-2">Date</th><th className="px-3 py-2">Heure exacte</th><th className="px-3 py-2">Multiplicateur</th><th className="px-3 py-2">Depuis début</th><th className="px-3 py-2">Intervalle précédent</th><th className="px-3 py-2">Hash / ID</th></tr></thead><tbody className="divide-y divide-cyan-100 dark:divide-cyan-900/40">{occurrences.map((occurrence, index) => <tr key={`${occurrence.id}-${occurrence.timestamp}`} className="bg-white/50 dark:bg-slate-900/40"><td className="px-3 py-2 font-bold text-slate-500 dark:text-slate-400">{index + 1}</td><td className="px-3 py-2 font-semibold text-slate-800 dark:text-slate-100">{formatDate(occurrence.timestamp)}</td><td className="px-3 py-2 font-mono text-slate-700 dark:text-slate-300">{formatTime(occurrence.timestamp)}</td><td className="px-3 py-2"><span className="rounded-md border border-violet-200 bg-violet-100 px-2 py-1 font-bold text-violet-800 dark:border-violet-800 dark:bg-violet-950/50 dark:text-violet-200">{occurrence.coefficient.toFixed(2)}x</span></td><td className="px-3 py-2 font-mono">{formatDuration(occurrence.offsetFromSlotStartSeconds)}</td><td className="px-3 py-2 font-mono">{formatDuration(occurrence.intervalFromPreviousMatchSeconds)}</td><td className="max-w-[280px] break-all px-3 py-2 font-mono text-[9px] text-slate-500 dark:text-slate-400">{occurrence.hash || occurrence.id}</td></tr>)}</tbody></table></div><p className="mt-2 text-[10px] text-slate-500 dark:text-slate-400">Le délai « depuis début » est calculé depuis {String(Math.floor(slotStartMinute / 60)).padStart(2, '0')}:{String(slotStartMinute % 60).padStart(2, '0')}. L’intervalle précédent concerne la précédente occurrence correspondante du même jour.</p></div>;
}

function ExpandButton({ expanded, count, onClick }: { expanded: boolean; count: number; onClick: () => void }) {
  return <button type="button" onClick={onClick} className="inline-flex items-center gap-1 rounded-lg border border-cyan-200 bg-white px-2.5 py-1.5 text-[10px] font-bold text-cyan-700 hover:bg-cyan-50 dark:border-cyan-800 dark:bg-slate-950 dark:text-cyan-300 dark:hover:bg-cyan-950/40">{expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}{expanded ? 'Masquer' : 'Voir'} {count} occurrence(s)</button>;
}

export const RecurrenceSummaryPanel: React.FC<RecurrenceSummaryPanelProps> = ({ records, sourceName }) => {
  const [minCoefficient, setMinCoefficient] = useState(15);
  const [maxCoefficient, setMaxCoefficient] = useState('');
  const [granularity, setGranularity] = useState<RecurrenceGranularity>(15);
  const [startTime, setStartTime] = useState('00:00');
  const [endTime, setEndTime] = useState('24:00');
  const [minimumDays, setMinimumDays] = useState(2);
  const [expandedSlot, setExpandedSlot] = useState<number | null>(null);
  const [expandedWeekday, setExpandedWeekday] = useState<number | null>(null);

  const filters = useMemo(() => {
    const [startHour, startMinute] = startTime.split(':').map(Number);
    const endParts = endTime === '24:00' ? [24, 0] : endTime.split(':').map(Number);
    const start = clampMinute((Number.isFinite(startHour) ? startHour : 0) * 60 + (Number.isFinite(startMinute) ? startMinute : 0));
    const end = endTime === '24:00' ? 1440 : Math.max(start + 1, clampMinute((Number.isFinite(endParts[0]) ? endParts[0] : 23) * 60 + (Number.isFinite(endParts[1]) ? endParts[1] : 59)));
    const parsedMax = Number(maxCoefficient);
    return { minCoefficient: Math.max(0, minCoefficient), maxCoefficient: maxCoefficient.trim() === '' || !Number.isFinite(parsedMax) ? null : Math.max(minCoefficient, parsedMax), granularityMinutes: granularity, startMinute: start, endMinute: Math.min(1440, end), minimumDays: Math.max(2, minimumDays) };
  }, [endTime, granularity, maxCoefficient, minCoefficient, minimumDays, startTime]);
  const summary = useMemo(() => analyzeRecurrences(records, filters), [filters, records]);
  const updateSlot = (slot: RecurrenceSlotSummary) => setExpandedSlot((current) => current === slot.startMinute ? null : slot.startMinute);
  const updateWeekday = (day: RecurrenceWeekdaySummary) => setExpandedWeekday((current) => current === day.weekday ? null : day.weekday);

  return <section className="rounded-2xl border border-cyan-200 bg-white p-5 shadow-xs dark:border-cyan-900/70 dark:bg-slate-900" aria-labelledby="recurrence-summary-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="rounded-xl bg-cyan-100 p-2 text-cyan-700 dark:bg-cyan-950/50 dark:text-cyan-300"><BarChart3 className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">SYNTHÈSE GLOBALE</p><h3 id="recurrence-summary-title" className="mt-1 text-base font-bold text-slate-900 dark:text-white">Récurrences observées dans les données</h3><p className="mt-1 max-w-3xl text-[11px] text-slate-500 dark:text-slate-400">Recherche les créneaux et les jours où une plage de multiplicateurs réapparaît sur plusieurs dates distinctes dans les données chargées.</p></div></div><span className="inline-flex items-center gap-1.5 rounded-full bg-cyan-50 px-3 py-1.5 text-[10px] font-semibold text-cyan-800 dark:bg-cyan-950/50 dark:text-cyan-200"><Info className="h-3.5 w-3.5" />Taux observés, pas une garantie</span></div>
    <div className="mt-4 rounded-xl border border-cyan-100 bg-cyan-50/50 p-3 dark:border-cyan-900/50 dark:bg-cyan-950/20"><p className="text-[10px] font-semibold text-cyan-950 dark:text-cyan-100">Source : {sourceName ?? 'Données actuellement chargées'} · {summary.totalValidRecords} tours valides · {summary.totalDates} date(s) couvertes</p><p className="mt-1 text-[10px] text-cyan-800 dark:text-cyan-200">Une récurrence est retenue uniquement si la plage choisie apparaît dans le créneau sur au moins deux dates distinctes ; plusieurs lignes le même jour restent des occurrences détaillées, pas des dates supplémentaires.</p></div>
    <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6"><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Multiplicateur min</span><input type="number" min="0" step="0.01" value={minCoefficient} onChange={(event) => setMinCoefficient(Number(event.target.value) || 0)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Multiplicateur max</span><input type="number" min="0" step="0.01" placeholder="Sans maximum" value={maxCoefficient} onChange={(event) => setMaxCoefficient(event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Créneau</span><select value={granularity} onChange={(event) => setGranularity(Number(event.target.value) as RecurrenceGranularity)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white"><option value={5}>5 minutes</option><option value={10}>10 minutes</option><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>60 minutes</option></select></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Heure début</span><input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white">Heure fin</span><input type="time" value={endTime === '24:00' ? '23:59' : endTime} onChange={(event) => setEndTime(event.target.value || '23:59')} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label><label className="space-y-1"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Minimum dates distinctes</span><input type="number" min="2" max="365" value={minimumDays} onChange={(event) => setMinimumDays(Math.max(2, Number(event.target.value) || 2))} className="w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></label></div>
    <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-950/40"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Tours correspondants</p><p className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{summary.matchingRecords}</p><p className="text-[10px] text-slate-500 dark:text-slate-400">entre {minCoefficient}x{filters.maxCoefficient === null ? '' : ` et ${filters.maxCoefficient}x`}</p></div><div className="rounded-xl border border-cyan-200 bg-cyan-50 p-3 dark:border-cyan-900/60 dark:bg-cyan-950/30"><p className="text-[10px] font-bold uppercase tracking-wider text-cyan-700 dark:text-cyan-300">Dates distinctes avec présence</p><p className="mt-1 text-xl font-bold text-cyan-950 dark:text-cyan-100">{summary.matchingDates}</p><p className="text-[10px] text-cyan-700 dark:text-cyan-300">taux global : {formatRecurrencePercent(summary.globalPresenceRate)}</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 dark:border-emerald-900/60 dark:bg-emerald-950/30"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-300">Créneau le plus régulier</p><p className="mt-1 text-base font-bold text-emerald-950 dark:text-emerald-100">{summary.strongestSlot?.label ?? '—'}</p><p className="text-[10px] text-emerald-700 dark:text-emerald-300">{summary.strongestSlot ? `${formatRecurrencePercent(summary.strongestSlot.presenceRate)} · ${summary.strongestSlot.occurrenceCount} occurrence(s)` : 'Aucune donnée'}</p></div></div>
    <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-[1040px] w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:bg-slate-950/70 dark:text-slate-400"><tr><th className="px-3 py-3 font-bold">Créneau</th><th className="px-3 py-3 font-bold">Dates analysées</th><th className="px-3 py-3 font-bold">Dates distinctes avec résultat</th><th className="px-3 py-3 font-bold">Taux observé</th><th className="px-3 py-3 font-bold">Occurrences</th><th className="px-3 py-3 font-bold">Plage observée</th><th className="px-3 py-3 font-bold">Détails</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{summary.slots.length > 0 ? summary.slots.map((slot) => <React.Fragment key={slot.startMinute}><tr className={expandedSlot === slot.startMinute ? 'bg-cyan-50/50 dark:bg-cyan-950/20' : ''}><td className="px-3 py-3 font-bold text-cyan-800 dark:text-cyan-200">{slot.label}</td><td className="px-3 py-3">{slot.totalDays}</td><td className="px-3 py-3">{slot.daysWithMatch}</td><td className="px-3 py-3 font-bold text-emerald-700 dark:text-emerald-300">{formatRecurrencePercent(slot.presenceRate)}</td><td className="px-3 py-3">{slot.occurrenceCount}</td><td className="px-3 py-3">{formatRecurrenceRange(slot.minimumCoefficient, slot.maximumCoefficient)}</td><td className="px-3 py-3"><ExpandButton expanded={expandedSlot === slot.startMinute} count={slot.occurrenceCount} onClick={() => updateSlot(slot)} /></td></tr>{expandedSlot === slot.startMinute && <tr><td colSpan={7} className="p-0"><OccurrenceDetails occurrences={slot.occurrences} title={`Occurrences du créneau ${slot.label}`} slotStartMinute={slot.startMinute} /></td></tr>}</React.Fragment>) : <tr><td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-500 dark:text-slate-400">Aucun créneau ne contient un multiplicateur dans la plage sélectionnée.</td></tr>}</tbody></table></div>
    <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-[900px] w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:bg-slate-950/70 dark:text-slate-400"><tr><th className="px-3 py-3 font-bold">Jour de la semaine</th><th className="px-3 py-3 font-bold">Jours analysés</th><th className="px-3 py-3 font-bold">Jours avec résultat</th><th className="px-3 py-3 font-bold">Taux observé</th><th className="px-3 py-3 font-bold">Occurrences</th><th className="px-3 py-3 font-bold">Plage observée</th><th className="px-3 py-3 font-bold">Détails</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{summary.weekdays.length > 0 ? summary.weekdays.map((day) => <React.Fragment key={day.weekday}><tr className={expandedWeekday === day.weekday ? 'bg-cyan-50/50 dark:bg-cyan-950/20' : ''}><td className="px-3 py-3 font-bold capitalize text-cyan-800 dark:text-cyan-200">{day.label}</td><td className="px-3 py-3">{day.totalDays}</td><td className="px-3 py-3">{day.daysWithMatch}</td><td className="px-3 py-3 font-bold text-emerald-700 dark:text-emerald-300">{formatRecurrencePercent(day.presenceRate)}</td><td className="px-3 py-3">{day.occurrenceCount}</td><td className="px-3 py-3">{formatRecurrenceRange(day.minimumCoefficient, day.maximumCoefficient)}</td><td className="px-3 py-3"><ExpandButton expanded={expandedWeekday === day.weekday} count={day.occurrenceCount} onClick={() => updateWeekday(day)} /></td></tr>{expandedWeekday === day.weekday && <tr><td colSpan={7} className="p-0"><OccurrenceDetails occurrences={day.occurrences} title={`Occurrences du ${day.label}`} slotStartMinute={filters.startMinute} /></td></tr>}</React.Fragment>) : <tr><td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-500 dark:text-slate-400">Aucun jour ne contient un résultat dans la plage sélectionnée.</td></tr>}</tbody></table></div>
    <p className="mt-3 text-[10px] text-slate-500 dark:text-slate-400">Les détails correspondent aux lignes réellement trouvées dans le JSON chargé. Ils ne constituent pas une prévision des événements futurs.</p>
  </section>;
};
